# Generated by Django 5.1.3 on 2024-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('republished', 'Republished'), ('closed', 'Closed')], default='draft', max_length=15),
        ),
    ]
