# Generated by Django 5.1.3 on 2024-11-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Radio'), ('checkbox', 'Checkbox'), ('text', 'Text')], max_length=20),
        ),
    ]
