# Generated by Django 5.1.3 on 2024-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
