# Generated by Django 5.1.3 on 2024-11-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_answer_selected_option'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
