# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='republished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='republished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('republished', 'Republished')], default='draft', max_length=11),
        ),
    ]
